// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwvzhxydntmjegzqpmvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3dnpoeHlkbnRtamVnenFwbXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3ODcxNzAsImV4cCI6MjA1ODM2MzE3MH0.ujyIvgDrvSrToaP4mXgsYDIfznS3KCrpPgB4L8Mdg_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);